const AppError = require("../utils/AppError");

const validateResponse = (schema, response) => {

    const result = schema.safeParse(response);

    if (!result.success) {

        console.log("\n========== RESPONSE VALIDATION FAILED ==========\n");

        console.dir(result.error.issues, {
            depth: null
        });

        console.log("\nActual Response:\n");

        console.dir(response, {
            depth: null
        });

        throw new AppError(
            "Invalid response generated by server",
            500
        );
    }

    return response;
};

module.exports = validateResponse;